---

nodeSelector:
  tier: monitoring

server:
  global:
    # Required for Thanos sidecar and querier ( data deduplication )
    external_labels:
      env: test
  # Prometheus basic config for Thanos: https://thanos.io/tip/components/sidecar.md/#example-basic-deployment
  extraFlags:
    - storage.tsdb.max-block-duration=2h
    - storage.tsdb.min-block-duration=2h
    - web.enable-lifecycle
    - web.enable-admin-api
  # Thanos sidecar basic config: https://thanos.io/tip/components/sidecar.md/#example-basic-deployment
  sidecarContainers:
    thanos:
      image: bitnami/thanos:0.31.0
      args:
        - sidecar
        - --tsdb.path
        - /data
        - --prometheus.url
        - http://localhost:9090
        - --http-address
        - 0.0.0.0:19191
        - --grpc-address
        - 0.0.0.0:10901
        - --objstore.config-file
        - /config/bucket.yml
      volumeMounts:
        - mountPath: /config
          name: bucket-s3
        # Same as Prometheus data volume mount and specified in --tsdb.path arg in this container
        - mountPath: /data
          name: storage-volume
      securityContext:
        runAsNonRoot: true
        # Same as Prometheus to be able to read data in /data path
        runAsUser: 65534
        runAsGroup: 65534
  extraVolumes:
    - name: bucket-s3
      configMap:
        name: bucket-s3
  service:
    # Port of Thanos sidecar
    gRPC:
      enabled: true
      servicePort: 10901
