---

nodeSelector:
  tier: storage

existingObjstoreSecret: bucket-s3

# https://thanos.io/v0.31/thanos/quick-tutorial.md/#querierquery
query:
  enabled: true
  recplicaCount: 3
  podLabels: {}
  nodeSelector:
    tier: storage
  logLevel: info
  logFormat: logfmt
  service:
    type: ClusterIP
    ports:
      http: 9090
    annotations: {}
  serviceGrpc:
    type: ClusterIP
    ports:
      grpc: 10901
    annotations: {}
  # Must match external_labels configured in Prometheus server
  replicaLabel: [env]
  stores:
    # Thanos sidecar gRPC port running as part of Prometheus server pod
    - dns+_grpc._tcp.prometheus-server.monitoring.svc.cluster.local:10901
    # Storage GW gRPC port
    - dns+_grpc._tcp.thanos-storegateway.monitoring.svc.cluster.local:10901
    # Storage GW gRPC port
    - dns+_grpc._tcp.thanos-receive.monitoring.svc.cluster.local:10901
  # https://github.com/thanos-io/thanos/blob/main/docs/service-discovery.md
  sdConfig: ""

queryFrontend:
  enabled: true
  recplicaCount: 1
  podLabels: {}
  nodeSelector:
    tier: storage
  logLevel: info
  logFormat: logfmt

bucketweb:
  enabled: true
  recplicaCount: 1
  podLabels: {}
  nodeSelector:
    tier: storage
  logLevel: info
  logFormat: json

# https://thanos.io/v0.31/thanos/quick-tutorial.md/#compactor
compactor:
  enabled: true

# https://thanos.io/v0.31/thanos/quick-tutorial.md/#store-gateway
# https://thanos.io/tip/components/store.md/
storegateway:
  enabled: true
  recplicaCount: 3
  podLabels: {}
  nodeSelector:
    tier: storage
  service:
    type: ClusterIP
    ports:
      http: 9090
      grpc: 10901
    annotations: {}
  extraFlags: []
    #- objstore.config-file=/config/bucket.yml
    #- http-address=0.0.0.0:9090
    #- grpc-address=0.0.0.0:10901
  # Same as bucket config for Thanos sidecar
  #extraVolumes:
  #  - name: bucket-s3
  #    configMap:
  #      name: bucket-s3
  #extraVolumeMounts:
  #  - mountPath: /config
  #    name: bucket-s3

# https://thanos.io/v0.31/thanos/quick-tutorial.md/#rulerrule
ruler:
  enabled: false

receive:
  enabled: true
  replicaCount: 3
  podLabels: {}
  nodeSelector:
    tier: storage
  tsdbRetention: 15d
  replicationFactor: 2
  logLevel: info
  logFormat: logfmt
  service:
    type: ClusterIP
    ports:
      http: 10902
      grpc: 10901
      # Configure Prometheus remoteWrite to connect to this port
      remote: 19291
    annotations: {}
  # Must match external_labels configured in Prometheus server
  replicaLabel: [env]

receiveDistributor:
  enabled: false

metrics:
  enabled: false
