---

nodeSelector:
  tier: storage

# https://thanos.io/v0.31/thanos/quick-tutorial.md/#querierquery
query:
  enabled: true
  recplicaCount: 3
  podLabels: {}
  nodeSelector:
    tier: storage
  logLevel: info
  logFormat: json
  # Must match external_labels configured in Prometheus server
  replicaLabel: [env]
  stores:
    # Thanos sidecar running as part of Prometheus server pod
    - prometheus-server.monitoring.svc.cluster.local:10901

queryFrontend:
  enabled: true
  recplicaCount: 1
  podLabels: {}
  nodeSelector:
    tier: storage
  logLevel: info
  logFormat: json

bucketweb:
  enabled: false
  recplicaCount: 1
  podLabels: {}
  nodeSelector:
    tier: storage
  logLevel: info
  logFormat: json

# https://thanos.io/v0.31/thanos/quick-tutorial.md/#compactor
compactor:
  enabled: false

# https://thanos.io/v0.31/thanos/quick-tutorial.md/#store-gateway
# https://thanos.io/tip/components/store.md/
storegateway:
  enabled: true
  extraFlags:
    - objstore.config-file=/config/bucket.yml
    - http-address=0.0.0.0:19191
    - grpc-address=0.0.0.0:10901
  # Same as bucket config for Thanos sidecar
  extraVolumes:
    - name: bucket-s3
      configMap:
        name: bucket-s3
  extraVolumeMounts:
    - mountPath: /config
      name: bucket-s3

# https://thanos.io/v0.31/thanos/quick-tutorial.md/#rulerrule
ruler:
  enabled: false

receive:
  enabled: false

receiveDistributor:
  enabled: false

metrics:
  enabled: false
