---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: false
  kubeProxyMode: "iptables"
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
- role: control-plane
- role: worker
  labels:
    tier: monitoring
- role: worker
  labels:
    tier: storage
- role: worker
  labels:
    tier: storage
- role: worker
  labels:
    tier: storage
